version: "3.1"

services:
  reverse_proxy:
    build: ./reverse_proxy
    user: nginx

  appserver:
    build:
       context: app
       dockerfile: Dockerfile
    container_name: appserver
    user: app
    ports:
      - "5005:5005"
    networks:
      - front-tier
      - back-tier

  jenkins:
    build:
      context: jenkins/
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - /tmp/jenkins:/var/jenkins_home #Remember that, the tmp directory is designed to be wiped on system reboot.
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  front-tier:
  back-tier:
    driver: overlay